Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  NewrelicServerlessControl:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: withoutNewrelic/index.handler
      Runtime: nodejs10.x
      CodeUri: '../../../dist/'
      Description: 'SAM local Lambda Resource for local running/debugging'
      MemorySize: 1024
      Timeout: 900
      Environment:
        Variables:
          ENVIRONMENT: 'mock'
          RPM: 5
          URI: ''
          TIME_DOING_WORK: 300
