Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  NewrelicServerlessStressTest:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: withNewrelic/index.handler
      Runtime: nodejs10.x
      CodeUri: '../../../dist/'
      Description: 'SAM local Lambda Resource for local running/debugging'
      MemorySize: 1024
      Timeout: 900
      Environment:
        Variables:
          ENVIRONMENT: 'mock'
          NEW_RELIC_LICENSE_KEY: 'super cool key' #TODO: replace with your license key
          NEW_RELIC_APP_NAME: 'newrelic-serverless-stress-test'
          NEW_RELIC_NO_CONFIG_FILE: true
          NEW_RELIC_LOG: 'stdout'
          RPM: 5
          URI: ''
          TIME_DOING_WORK: 300
